node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
       def app = docker.build("klehmann89/docker-nodejs-demo3:latest", '.').push()
     }
   }

   stage('Deploy') {
         
                  echo 'Deploying the application on Docker'
                  sh "docker rm -f test-nodejs"
                   sh "docker run -p 3000:3000 -d  --name test-nodejs klehmann89/docker-nodejs-demo3:latest" 
               
           }
   
}
